### ISSUE TITLE
Ter dois elementos iguais que tem a função _onClick mapeada faz com que apenas a função do primeiro execute

### ISSUE THREAD

**Issue by munhozotavio** [mundorum/oid#1]
### Passos para replicar
Exemplo: Adicionar dois elementos increase-oid que mapeiam a função _onClick:
~~~html
<increase-oid rate="5" publish="click~increase/bar"></increase-oid>
<increase-oid rate="3" publish="click~increase/bar"></increase-oid>                     
~~~
Clicar no primeiro botão
Clicar no segundo botão

### Resultado esperado
Que ambas as funções onClick executem

### Resultado obtido
Só executa a função onClick do primeiro elemento

**Comment by santanche** [comment]
Corrected bug: only the first instance's event handler works for each component. #a408759
